# Generated by Django 2.2.3 on 2019-07-29 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('gender', models.TextField()),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.BooleanField(default=False)),
                ('risk', models.IntegerField()),
                ('invested', models.DecimalField(decimal_places=2, max_digits=6)),
                ('lastChange', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chatbotNextChange', models.DecimalField(decimal_places=2, max_digits=5)),
                ('newspostNextChange', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_participant', models.BooleanField()),
                ('month', models.IntegerField()),
                ('available', models.DecimalField(decimal_places=2, max_digits=6)),
                ('invested', models.DecimalField(decimal_places=2, max_digits=6)),
                ('from_notification', models.BooleanField(default=False)),
                ('from_button', models.BooleanField(default=False)),
                ('name', models.TextField(null=True)),
                ('action', models.TextField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.DecimalField(decimal_places=2, default=1000.0, max_digits=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Balance',
                'verbose_name_plural': 'Balances',
            },
        ),
    ]
