# Generated by Django 2.2.1 on 2019-06-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='risk',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
