# Generated by Django 2.2.1 on 2019-06-08 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_portfolio_risk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
