# Generated by Django 2.2.3 on 2019-07-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20190729_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('available', models.DecimalField(decimal_places=2, max_digits=6)),
                ('invested', models.DecimalField(decimal_places=2, max_digits=6)),
                ('name', models.TextField()),
                ('action', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
        migrations.RemoveField(
            model_name='message',
            name='action',
        ),
        migrations.RemoveField(
            model_name='message',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='message',
            name='available',
        ),
        migrations.RemoveField(
            model_name='message',
            name='invested',
        ),
        migrations.RemoveField(
            model_name='message',
            name='month',
        ),
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
    ]
