# Generated by Django 2.0.7 on 2019-06-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_remove_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investedbalance',
            name='amount',
        ),
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=6),
        ),
    ]
