# Generated by Django 2.0.7 on 2019-07-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_auto_20190620_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='positive',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
