# Generated by Django 2.0.7 on 2019-07-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_newspost_positive'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='nextChange',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
            preserve_default=False,
        ),
    ]
