# Generated by Django 2.2.3 on 2019-07-29 22:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0006_auto_20190729_2255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action',
            new_name='UserAction',
        ),
        migrations.AlterModelOptions(
            name='useraction',
            options={'verbose_name': 'UserAction', 'verbose_name_plural': 'UserActions'},
        ),
    ]
