# Generated by Django 2.0.7 on 2019-07-19 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_portfolio_nextchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='positive',
        ),
        migrations.RemoveField(
            model_name='newspost',
            name='text',
        ),
    ]
