# Generated by Django 2.0.7 on 2019-07-19 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_auto_20190719_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'verbose_name': 'Balance', 'verbose_name_plural': 'Balances'},
        ),
        migrations.AlterModelOptions(
            name='investedbalance',
            options={'verbose_name': 'Invested Balance', 'verbose_name_plural': 'Invested Balances'},
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'verbose_name': 'Month', 'verbose_name_plural': 'Months'},
        ),
        migrations.AlterModelOptions(
            name='newspost',
            options={'verbose_name': 'Newspost', 'verbose_name_plural': 'Newsposts'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
