# Generated by Django 2.2.3 on 2019-07-29 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_auto_20190729_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='action',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='portfolio',
            field=models.CharField(max_length=128),
        ),
    ]
