# Generated by Django 2.0.7 on 2019-07-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_auto_20190720_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='accurate',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
