# Generated by Django 2.0.7 on 2019-07-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_newspost_accurate'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='fakeChange',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
            preserve_default=False,
        ),
    ]
