# Generated by Django 2.0.7 on 2019-07-21 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_auto_20190722_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='chatbotChange',
            new_name='chatbotNextChange',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='newspostChange',
            new_name='newspostNextChange',
        ),
    ]
