# Generated by Django 2.2.3 on 2019-07-30 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_auto_20190730_0116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dismissnotificationcount',
            options={'verbose_name': 'Dismiss Notification Count', 'verbose_name_plural': 'Dismiss Notification Counts'},
        ),
        migrations.AlterModelOptions(
            name='useraction',
            options={'verbose_name': 'User Action', 'verbose_name_plural': 'User Actions'},
        ),
    ]
