# Generated by Django 2.2.3 on 2019-07-30 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='invested_change',
            new_name='profit',
        ),
    ]
