# Generated by Django 2.2.3 on 2019-07-30 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_auto_20190730_2326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='total_amount',
            new_name='total',
        ),
    ]
