# Generated by Django 2.2.3 on 2019-08-28 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0016_questionnaireresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='FallbackCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fallback Count',
                'verbose_name_plural': 'Fallback Counts',
            },
        ),
        migrations.DeleteModel(
            name='DismissNotificationCount',
        ),
    ]
